# Generated by Django 6.0 on 2025-12-14 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        help_text="Material Icon name or URL", max_length=100
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("maintainer", models.CharField(blank=True, max_length=100)),
                ("image", models.CharField(max_length=200)),
                ("env_vars", models.JSONField(default=dict)),
                ("ports", models.JSONField(default=list)),
                ("volumes", models.JSONField(default=list)),
                (
                    "installed_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status", models.CharField(default="stopped", max_length=20)),
                ("expose_public", models.BooleanField(default=False)),
                ("expose_vpn", models.BooleanField(default=False)),
                ("domain_prefix", models.CharField(blank=True, max_length=100)),
                (
                    "auth_protected",
                    models.BooleanField(
                        default=False, help_text="Enable Anubis protection"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(default="General", max_length=50)),
                ("icon", models.CharField(max_length=100)),
                ("docker_compose_template", models.TextField()),
                ("form_schema", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("vpn_enabled", models.BooleanField(default=False)),
                ("ssh_port", models.IntegerField(default=22)),
                ("public_dashboard", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
